/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'qxue' at '5/12/16 12:49 PM' with Gradle 2.3
 *
 * @author qxue, @date 5/12/16 12:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
